# Generated by Django 5.0 on 2024-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
