# Generated by Django 5.0 on 2024-01-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
