# Generated by Django 5.0 on 2024-01-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_borrow_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookreview',
            name='review_description',
        ),
        migrations.AddField(
            model_name='book',
            name='average_reviews',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
