# Generated by Django 5.0 on 2024-01-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_category_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbookreview',
            options={'ordering': ['-id']},
        ),
    ]
